/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'case-studies': CaseStudy;
    blog: Blog;
    tags: Tag;
    testimonials: Testimonial;
    faqs: Faq;
    'contact-submissions': ContactSubmission;
    comments: Comment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-media': SiteMedia;
  };
  globalsSelect: {
    'site-media': SiteMediaSelect<false> | SiteMediaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Who can sign in to this admin. Keep it to the people who need it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Shown in the admin instead of the bare email address.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Every image and video on the site lives here. Upload once, then point a case study, journal post or page slot at it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * What the picture shows, in a sentence — read aloud by screen readers and shown if the file fails to load.
   */
  alt: string;
  /**
   * Tagged images appear in the site gallery, filterable by tag.
   */
  tags?: (string | Tag)[] | null;
  /**
   * The most recently updated featured photo fills the full-width gallery band on the homepage.
   */
  featured?: boolean | null;
  /**
   * Shown next to the image in the gallery lightbox.
   */
  description?: string | null;
  /**
   * When the photo was taken — shown in the gallery lightbox.
   */
  dateTaken?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  title: string;
  /**
   * Leave blank to generate from the title.
   */
  slug: string;
  publishedAt?: string | null;
  tags?: (string | Tag)[] | null;
  /**
   * Short teaser shown on cards and used as the SEO description.
   */
  excerpt?: string | null;
  roles?: string | null;
  collaborators?:
    | {
        role: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  location?: string | null;
  year?: number | null;
  mainMedia?: (string | null) | Media;
  content?:
    | (
        | {
            description: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            /**
             * One sentence, set large — the point of the project rather than a description of it. Use sparingly; two or three in a case study is plenty.
             */
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'statement';
          }
        | {
            /**
             * Optional kicker above the heading. Numbering them helps a long study.
             */
            eyebrow?: string | null;
            heading: string;
            /**
             * Optional lead paragraph. Add Text blocks below for the rest.
             */
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
        | {
            swatches: {
              name: string;
              hex: string;
              /**
               * What the colour is for. This is the part clients actually read.
               */
              usage?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'palette';
          }
        | {
            faces: {
              family: string;
              role?: string | null;
              /**
               * Shown large as the specimen. Leave blank to use the typeface name itself.
               */
              sample?: string | null;
              notes?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'typeSpecimen';
          }
        | {
            media: string | Media;
            /**
             * Photographs usually want full bleed. Screenshots want framing — a browser window running to the page edge reads as the page itself rather than as a picture of one.
             */
            display?: ('full' | 'framed') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            images: {
              media: string | Media;
              /**
               * Optional tag under the image. This is how you pair a desktop and a mobile shot in one row.
               */
              label?: string | null;
              id?: string | null;
            }[];
            /**
             * Optional — describes the row as a whole.
             */
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * Leave blank to generate from the title.
   */
  slug: string;
  publishedAt?: string | null;
  /**
   * Shown as “Written by …” on the post.
   */
  author?: string | null;
  tags?: (string | Tag)[] | null;
  /**
   * Short teaser shown on cards and used as the SEO description.
   */
  excerpt?: string | null;
  mainMedia?: (string | null) | Media;
  /**
   * The post itself — headings, text, images and video all live here.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Drag rows in this list to set the order they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  _order?: string | null;
  name: string;
  /**
   * e.g. "Team Lead — Acme Corp"
   */
  role?: string | null;
  /**
   * e.g. "Acme Corp"
   */
  company?: string | null;
  /**
   * Optional company logo shown beside the quote.
   */
  companyLogo?: (string | null) | Media;
  /**
   * A photo of the person.
   */
  image: string | Media;
  quote: string;
  /**
   * Only featured testimonials show on the site.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Drag rows in this list to set the order they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  _order?: string | null;
  question: string;
  /**
   * Keep it to a short paragraph or two. Links are fine.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Uncheck to hide this question from the site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  topic?: ('project' | 'local' | 'care' | 'other') | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  /**
   * The journal post or case study this comment belongs to.
   */
  post:
    | {
        relationTo: 'blog';
        value: string | Blog;
      }
    | {
        relationTo: 'case-studies';
        value: string | CaseStudy;
      };
  name: string;
  /**
   * Never shown publicly — only used to identify the commenter.
   */
  email: string;
  body: string;
  /**
   * Comments stay hidden until this is checked.
   */
  approved?: boolean | null;
  /**
   * How many readers liked this comment.
   */
  likes?: number | null;
  voters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tags?: T;
  featured?: T;
  description?: T;
  dateTaken?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  tags?: T;
  excerpt?: T;
  roles?: T;
  collaborators?:
    | T
    | {
        role?: T;
        name?: T;
        id?: T;
      };
  location?: T;
  year?: T;
  mainMedia?: T;
  content?:
    | T
    | {
        text?:
          | T
          | {
              description?: T;
              id?: T;
              blockName?: T;
            };
        statement?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        section?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        palette?:
          | T
          | {
              swatches?:
                | T
                | {
                    name?: T;
                    hex?: T;
                    usage?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        typeSpecimen?:
          | T
          | {
              faces?:
                | T
                | {
                    family?: T;
                    role?: T;
                    sample?: T;
                    notes?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              display?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?:
                | T
                | {
                    media?: T;
                    label?: T;
                    id?: T;
                  };
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  author?: T;
  tags?: T;
  excerpt?: T;
  mainMedia?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  company?: T;
  companyLogo?: T;
  image?: T;
  quote?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  topic?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  name?: T;
  email?: T;
  body?: T;
  approved?: T;
  likes?: T;
  voters?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The fixed images built into the page layouts. Each field says what the shot needs to be — leave one blank and the brief shows in its place on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-media".
 */
export interface SiteMedia {
  id: string;
  home?: {
    /**
     * One finished project, wide. Building in full, shot straight on in good light. Sits full-bleed under the headline, so keep the subject off the extreme edges.
     */
    hero?: (string | null) | Media;
    /**
     * Close crop on craft: a material joint, a hand at work, a finished edge. Tall — it fills a portrait column beside the “most construction websites…” copy.
     */
    statement?: (string | null) | Media;
    /**
     * Edge-to-edge site or interior shot. Wide, quiet, no text overlay. A visual pause between the work grid and the testimonials.
     */
    band?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-media_select".
 */
export interface SiteMediaSelect<T extends boolean = true> {
  home?:
    | T
    | {
        hero?: T;
        statement?: T;
        band?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}